### ISSUE TITLE
Expect data: Not contains

### ISSUE THREAD

**Issue by AntonAderum** [aviaviavi/curl-runnings#15]
Hi!

I've been playing around with this project and something i ran into straight away
was not being able to say: "Dont find this in the response".

For example if I would like to make sure no public data is sent if I'm not authorized:

```
....
expectData:
  notContains:
    - keyValueMatch:
        key: isPublic
        value: true
...
```

Maybe this is possible to do, but I looked through the examples and couldn't find anything about it.

Regards
