### ISSUE TITLE
overwrite content type

### ISSUE THREAD

**Issue by ph-kvieth** [aviaviavi/curl-runnings#78]
I need for testing my api to change the content type to  
requestMethod: PATCH
content-type:  "application/merge-patch+json"

**Comment by aviaviavi** [comment]
Hi @ph-kvieth. Apologies for the slow response here.

You can achieve this by setting the following in your test case:

```yaml
  ...
  requestMethod: PATCH
  headers: "Content-Type: application/merge-patch+json"
  ... 
```

Let me know if you have any issues here.
